plugins {
    id 'com.android.library'
    id 'jacoco'
}
apply plugin: 'kotlin-android'

android {
    compileSdk pcam_compileSdk.toInteger()

    defaultConfig {
        minSdkVersion pcam_minSdk.toInteger()
        //Waiting for api 32 sources
        //noinspection OldTargetApi

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildFeatures {
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.toVersion(pcam_javaVersion)
        targetCompatibility JavaVersion.toVersion(pcam_javaVersion)
    }
    kotlinOptions {
        jvmTarget = pcam_javaVersion
    }
    namespace 'com.particlesdevs.photoncamera.circularbarlib'
    lint {
        targetSdk pcam_targetSdk.toInteger()
    }
    testOptions {
        targetSdk pcam_targetSdk.toInteger()
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.11.0'
    implementation 'androidx.test:monitor:1.7.2'
    testImplementation 'org.testng:testng:7.11.0'
    implementation 'androidx.test.ext:junit:1.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'junit:junit:4.13.2'

/*    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'*/
}
repositories {
    mavenCentral()
}